FROM node:24.11.1-alpine

ENV APP_ROOT /var/www

ENV LANG=ja_JP.UTF-8
ENV LANGUAGE=ja_JP.UTF-8
ENV TZ=Asia/Tokyo

RUN apk update && \
  apk add --no-cache git bash curl musl musl-utils musl-locales tzdata libc6-compat && \
  npm i -g create-react-app jshint

RUN mkdir -p $APP_ROOT
WORKDIR $APP_ROOT

COPY ./package.json $APP_ROOT
COPY ./package-lock.json $APP_ROOT
RUN npm install

COPY . $APP_ROOT

# CMD [ "npm", "run", "dev" ]
